### ISSUE TITLE
Take into account image tags

### ISSUE THREAD

**Issue by benizar** [siose-innova/siose-docker-library#2]
This [Makefile]( https://github.com/siose-innova/siose-docker-library/blob/master/Makefile) can build images and look for their base images, no matters if they are on the registry or have to be compiled as prerequisites. However, it considers always the `latest` tag for every image.

I will modify this Makefile to take into account tags also. I will extend the current strategy of building rules from defines.

Any suggestions on how to do this?

**Comment by quommit** [comment]
@torrespri @benizar  
Using untagged images is almost certainly a pitfall as far as reproducibility is concerned. In fact, it should be a no-opt when basing your images on distributions like Alpine Linux, whose release cycle is blazing fast compared to Debian or Ubuntu. I myself have already experimented reproducibility issues in a very short time frame due to using `alpine:latest`. I mean that kind of *"it worked last week but not anymore"* issue. I learned the lesson and try to avoid untagged images since then.  
As for the building strategy, an alternative would be searching directories two levels deep, so that instead of searching paths like:  
  
```
lib
 |_ image-name
      |_ Dockerfile
```  
  
we would go one level deeper as in:  
  
```
lib
  |_ image-name
       |_ tag
            |_ Dockerfile
```  
  
This is roughly how Docker files in mdillon/postgis repo are organized. I use to follow this convention to locally store my Docker files and to date it's been ok for naming images in my local registry.

**Comment by quommit** [comment]
@torrespri @benizar  
Forgot mentioning that the tagging strategy also involves avoiding references to untagged images in the `FROM` instruction within a Dockerfile. In the end it's a question of sticking to a common convention.

**Comment by benizar** [comment]
Ok, let me a couple of days and I'll try to read tags also.

I think that it's easy to get tags when source images are official images from docker hub. However, keeping one different tag for our own images can be difficult to maintain. This is why I considered a tag for each library version (commit or github version).

@quommit what do you think about this approach?

Can you provide an example for any Dockerfile in this repository?

**Comment by quommit** [comment]
Have a look at pull request #4.  
The point is `siose-innova/postgresql:10.2` is a copy of the official image `postgresql:10.2-alpine` with a few additions and bare of a database cluster volume. In the end it still is PostgreSQL 10.2 and we're gonna use it for the same purposes as if it were the official. The same would apply to `siose-innova/postgis:2.4.3` for instance. These are base products, and always keeping and having explicit version info about our base products is convenient. Once we move away from base products, let's say a `siose-innova/siose2005-mf2:1.0` image or alike, we get into our own versioning or tagging scope.

**Comment by benizar** [comment]
OK, this is perfect. I'm finishing some tests with the new Makefile version and everything seems to be working fine. Tonight, I will push my changes and merge [#4](https://github.com/siose-innova/siose-docker-library/pull/4). Then, we will need to think about a tagging scheme.

**Comment by benizar** [comment]
Now, the Makefile takes into account docker image tags.

First, it follows the pattern suggested by @quommit to define image tags, so any future Dockerfiles should be stored like:
```
lib
  |_ image-name
       |_ tag
            |_ Dockerfile
```  
In the Makefile setup we can read image dependencies (`FROM vendor/name:tag`) and compile them as rule prerequisites. Separating pull prerequisites (from dockerhub) and local-library prerequisites (other images contained in this lib). This can be improved by implementing other possibilities (e.g. pulling images from dockerhub, that were pushed by this Makefile).

In its current version, this Makefile doesn't take care of the vendor part of the docker image parent (`FROM vendor/name:tag`). It probably works, but It would be better if we separate all images by considering the vendor. As for example, it would allow us to remove only `sioseinnova/` images (or any non-official images) at once, with a single command like "make mostlyclean".

The main problem of using GNU Make for doing this, is that colon is used for separating docker image names from tags (e.g. vendor/name:tag), but it is also a special character in Makefiles, it divides a rule into targets and prerequisites. Our solution is to transpose ":" to ".." when doing make tasks, so we have make targets like "postgis..2.4.3". However, when we build and push images, it becomes to the docker format (e.g. postgis:2.4.3) .
